# Generated by Django 4.1.8 on 2023-05-04 20:45

import django.core.validators
from django.db import migrations, models
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('extras', '0092_delete_jobresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgpCommunityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.TextField(blank=True)),
                ('devices_list', models.ManyToManyField(to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Community Groups',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='BgpCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\d+:\\d+')])),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('devices_list', models.ManyToManyField(to='dcim.device')),
                ('parentgroup', models.ManyToManyField(related_name='communities', to='netbox_bgp.bgpcommunitygroup')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ('community', 'id'),
            },
        ),
    ]
