# Generated by Django 4.1.8 on 2023-04-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_bgp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='devices',
        ),
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='dcim.device'),
        ),
    ]
