# Generated by Django 4.1.8 on 2023-04-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunity',
            name='index',
        ),
    ]
