# Generated by Django 4.1.8 on 2023-04-25 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0002_remove_bgpcommunity_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpcommunity',
            options={'ordering': ('name', 'community'), 'verbose_name_plural': 'Communities'},
        ),
        migrations.AddField(
            model_name='bgpcommunity',
            name='community',
            field=models.CharField(default='65000.500', max_length=64, validators=[django.core.validators.RegexValidator('\\d+:\\d+')]),
            preserve_default=False,
        ),
    ]
