# Generated by Django 4.1.8 on 2023-04-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_bgp', '0003_remove_bgpcommunitygroup_devices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='devices',
        ),
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.device'),
        ),
    ]
