# Generated by Django 4.1.8 on 2023-04-27 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_bgp', '0004_remove_bgpcommunitygroup_devices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunity',
            name='parentgroup',
        ),
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='devices',
        ),
        migrations.AddField(
            model_name='bgpcommunity',
            name='parentgroup',
            field=models.ManyToManyField(blank=True, related_name='+', to='netbox_bgp.bgpcommunitygroup'),
        ),
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.device'),
        ),
    ]
