# Generated by Django 4.1.8 on 2023-05-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_bgp', '0008_remove_bgpcommunitygroup_devices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bgpcommunitygroup',
            options={'ordering': ('name', 'id'), 'verbose_name_plural': 'Community Groups'},
        ),
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='devices',
        ),
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='devices_list',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.device'),
        ),
    ]
