# Generated by Django 4.1.8 on 2023-05-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_bgp', '0009_alter_bgpcommunitygroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='devices_list',
        ),
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='devices_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.device'),
        ),
    ]
