# Generated by Django 4.1.8 on 2023-05-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0171_cabletermination_change_logging'),
        ('netbox_bgp', '0010_remove_bgpcommunitygroup_devices_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='devices_list',
        ),
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='devices_list',
            field=models.ManyToManyField(to='dcim.device'),
        ),
    ]
