# Generated by Django 4.1.8 on 2023-05-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0011_remove_bgpcommunitygroup_devices_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunity',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='bgpcommunity',
            name='parentgroup',
            field=models.ManyToManyField(blank=True, related_name='communities', to='netbox_bgp.bgpcommunitygroup'),
        ),
    ]
