# Generated by Django 4.1.8 on 2023-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0012_remove_bgpcommunity_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bgpcommunity',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
