# Generated by Django 4.1.8 on 2023-05-02 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0013_bgpcommunitygroup_comments_alter_bgpcommunity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bgpcommunitygroup',
            name='comments',
        ),
    ]
