# Generated by Django 4.1.8 on 2023-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_bgp', '0014_remove_bgpcommunitygroup_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgpcommunitygroup',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
